### ISSUE TITLE
Missing credentials in config

### ISSUE THREAD

**Issue by jjangga0214** [awsdocs/aws-javascript-developer-guide-v2#9]
While following the tutorial [here](https://github.com/awsdocs/aws-javascript-developer-guide-v2/blob/master/s3-example-photo-album.md), I got error **"Missing credentials in config"**.  As like below, the code is quite simple, but don't know why the error occurs even though I think I fully followed the prerequirements for the tutorial. I am curious to when the error message **"Missing credentials in config"** appears, so that I might guess the reason. Is this because AWS has changed or am I making something wrong? 
It would be truly thankful if you let me know the right answer.

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.255.1.min.js"></script>
    <script>
        var bucketName = 'mama-swedenhouse-resources';
        var bucketRegion = 'ap-northeast-2';
        var identityPoolId = 'ap-northeast-2:f4250b2e-5d77-4413-bc3a-34c4xxxxxxxx'; //just hiding last 8 letters on this github issue 

        AWS.config.update({
            region: bucketRegion,
            credentials: new AWS.CognitoIdentityCredentials({
                identityPoolId: identityPoolId
            })
        });

        var s3 = new AWS.S3({
            apiVersion: '2006-03-01',
            params: {
                Bucket: bucketName
            }
        });

        function uploadPhoto() {

            var files = document.getElementById('test-file-input').files;
            if (!files.length) {
                return alert('Please choose a file to upload first.');
            }
            var file = files[0];
            var fileName = file.name;

            s3.upload({
                Key: fileName + ' ' + Math.floor(Date.now()),
                Body: file,
                ACL: 'public-read'
            }, function (err, data) {
                if (err) {
                    console.log(err);
                    return console.log('There was an error uploading your photo: ', err.message);
                }
                console.log('Successfully uploaded photo.');
            });
        };
    </script>
</head>

<body>
<section>
    <input type="file" name="test-file-input" id="test-file-input" accept="image/*">
    <button id="uplaod-btn" onclick="uploadPhoto();">업로드</button>
</section>
</body>

</html>
```

##### Error message
```
Error: Missing credentials in config
    at constructor.fail (aws-sdk-2.255.1.min.js:50)
    at constructor.validateStructure (aws-sdk-2.255.1.min.js:50)
    at constructor.validateMember (aws-sdk-2.255.1.min.js:50)
    at constructor.validate (aws-sdk-2.255.1.min.js:50)
    at constructor.<anonymous> (aws-sdk-2.255.1.min.js:49)
    at constructor.callListeners (aws-sdk-2.255.1.min.js:51)
    at constructor.emit (aws-sdk-2.255.1.min.js:51)
    at constructor.emitEvent (aws-sdk-2.255.1.min.js:50)
    at constructor.e (aws-sdk-2.255.1.min.js:50)
    at a.runTo (aws-sdk-2.255.1.min.js:52)
aws-s3-upload.html:48 There was an error uploading your photo:  Missing credentials in config
```

**Comment by jlmortola** [comment]
hi there! did u get to solve this? I'm having the same problem. thanks!

**Comment by jlmortola** [comment]
ok got it working setting the credentials like this:

```
AWS.config.region = 'REGION';
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'IDENTITY_POOL_ID',
});
```

hope this helps!

**Comment by Paul-B-AWS** [comment]
This is a fairly old issue, but I wanted to circle back and let you know about some updates.
- @jjangga0214 I _think_ your problem might have been that the first "identityPoolId" in the AWS.config block has a lower-case "i", but it needs to have an upper-case "I". See the [current home](https://github.com/awsdocs/aws-javascript-developer-guide-v2/blob/master/doc_source/s3-example-photo-album.md#configuring-the-sdk) of the page you referred to in your original post. (Or see the [doc Web page](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html#s3-example-photo-album-configure-sdk).)
Notice the character case of the property name.
- @jlmortola Thanks for showing that alternative form. Many of the examples use that form instead of the form that exists in this example's code.
The advantage of the form you show is that you can copy it directly from the Amazon Cognito console (**Cognito** -->  [Your Identity Pool] --> **Sample code**, but be sure to select "JavaScript" from the drop-down list).
- As a final note:
I have also added a view-only example. It's simpler, but it's content is more detailed. If you are interested, see the new example [here](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photos-view.html).
